### DISCUSSION TITLE
Credenziali incorrette?

### DISCUSSION THREAD

**Discussion by G3z** [aturri/ha-zcsazzurro#46] [Q&A]
Buonasera,
non capisco perchè l'integrazione mi riporta che le credenziali non sono corrette
ho verificato il seriale ed è corretto

da postman funzionano questi headers
```
Authorization: Zcs eH****0
Client: G***i
```

questo e quanto ho scritto nel file YAML
```yaml
zcsazzurro:
  auth_key: "Zcs eH***0"
  client_code: G***i
```

nel log di debug del componente HA però vedo 
`2024-01-29 16:42:58.703 WARNING (MainThread) [custom_components.zcsazzurro.api] Unable to parse result from ZCS Azzurro portal: NOT AUTHENTICATED`

cosa sbaglio ?
